apiVersion: v1
kind: Secret
metadata:
  name: martin-db-password
type: Opaque
data:
  username: Z3Vlc3Rib29r
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: martin-redis-password
type: Opaque
data:
  password: cGFzc3dvcmQ=
